CREATE TABLE IF NOT EXISTS `trade_user_address` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `user_id` bigint NOT NULL COMMENT '用户编号',
  `receiver_name` varchar(64) NOT NULL COMMENT '收货人姓名',
  `receiver_mobile` varchar(20) NOT NULL COMMENT '收货人手机号',
  `province_code` varchar(32) NOT NULL COMMENT '省编码',
  `province_name` varchar(64) NOT NULL COMMENT '省名称',
  `city_code` varchar(32) NOT NULL COMMENT '市编码',
  `city_name` varchar(64) NOT NULL COMMENT '市名称',
  `district_code` varchar(32) DEFAULT '' COMMENT '区编码',
  `district_name` varchar(64) DEFAULT '' COMMENT '区名称',
  `detail_address` varchar(255) NOT NULL COMMENT '详细地址',
  `postal_code` varchar(20) DEFAULT '' COMMENT '邮编',
  `is_default` tinyint NOT NULL DEFAULT 0 COMMENT '是否默认：0-否 1-是',
  `status` tinyint NOT NULL DEFAULT 0 COMMENT '状态：0-启用 1-禁用',
  `creator` varchar(64) DEFAULT '',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` smallint NOT NULL DEFAULT 0,
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`, `tenant_id`, `deleted`),
  KEY `idx_user_default` (`user_id`, `is_default`, `tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
